CREATE DATABASE  tugas1;
USE tugas1;

CREATE TABLE IF NOT EXISTS books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  author VARCHAR(100) NOT NULL,
  year INT NOT NULL,
  category VARCHAR(50) NOT NULL,
  cover VARCHAR(255) DEFAULT NULL,
  status ENUM('tersedia','dipinjam') NOT NULL DEFAULT 'tersedia',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);